import { animetriximg, quibbleimg, sso, trimImg, wasteeasy } from "./index";
export const projectArray = [
    {
        name: "LyricSense",
        description: "An AI tool that breaks down complex song lyrics to reveal the emotions and insights behind the song, Enter your favorite song and discover why it makes you feel happy, sad, or excited.",
        image: animetriximg,
        type: "open source",
        hostedLink: "https://lyricsense-ai.vercel.app",
        githubLink: "https://www.github.com/Tirth-chokshi/LyricSense-AI",
    },
    {
        name: "vocalcare",
        description: "Solution for Speech Language Therapy.",
        image: wasteeasy,
        type: "Smart India Hackthon Project",
        hostedLink: "https://vocalcare.vercel.app",
        githubLink: "https://www.github.com/Tirth-chokshi/vocalcare",
    },
    {
        name: "QuerySage-AI",
        description: "Chatgpt for your Databases, Interact with your Database in Natural Language",
        image: sso,
        type: "Open Source",
        hostedLink: "https://querysage-ai.vercel.app/login",
        githubLink: "https://www.github.com/Tirth-chokshi/QuerySage-ai",
    },
    {
        name: "VideoTapeVisuals",
        description: "Generate your business car in style of American psycho, Your premier destination for crafting business cards that would make Patrick Bateman 🔪 envious.",
        image: trimImg,
        type: "open source",
        hostedLink: "https://videotapevisuals.vercel.app",
        githubLink: "https://github.com/Tirth-chokshi/VideoTapeVisuals",
    },
    {
        name: "Persona Builder",
        description: "Persona Builder is a robust solution designed to help users efficiently compile and analyze comprehensive profiles of companies or individuals. By gathering and synthesizing data from multiple reliable sources, Persona Builder offers a holistic view for networking, business development, and research purposes.",
        image: quibbleimg,
        type: "Hackthon Porject",
        hostedLink: "",
        githubLink: "https://github.com/Tirth-chokshi/persona-builder",
    },
    // {
    //     name: "Synthia",
    //     description: "Synthia is a lightweight and beginner-friendly interpreted programming language developed in Rust. With a simple, intuitive syntax and a focus on ease of use, Synthia is perfect for both newcomers to programming and experienced developers looking for a flexible scripting language",
    //     image: synthiaimg,
    //     type: "open source",
    //     hostedLink: "",
    //     githubLink: "https://www.github.com/shivabhattacharjee/synthia",
    // },
    // {
    //     name: "Recordify",
    //     description: "Recordify is a chrome extension that allows users to record their screen and audio. It is developed in vanilla JavaScript . Users can record their screen and audio with a single click and save the recording as a webm file.",
    //     image: recordify,
    //     type: "open source",
    //     hostedLink: "",
    //     githubLink: "https://www.github.com/shivabhattacharjee/recordify",
    // },
];
